### ISSUE TITLE
Failure to quit Firefox on Beta with closing multiple tab dialog present.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1075]
If a test finishes with more than one browser tab open, we fail to shutdown because of the closing mutli-tab dialog warning. This works correctly when testing against Release. Something in beta has changed; either Iris is not correctly running the LIKE_NEW profile, or the LIKE_NEW profile isn't compatible with Beta. We need LIKE_NEW because it disables the disruptive dialog.

Our test pass next week is going to be difficult unless this is fixed.

**Comment by mwobensmith** [comment]
I checked in another fix. Now, in the `LIKE_NEW` and `TEN_BOOKMARK` profiles, we have turned all three preferences to `false` so that the dialog will not appear.

For tests that use `BRAND_NEW`, this behaves very differently. Unlike the above two profiles, which we have created already and can modify to our wishes, `BRAND_NEW` does not exist. It just tells Firefox to create a completely new profile, with its own defaults, the same way a first-time user of Firefox would do. Because of this, we can't write prefs to this profile, as it doesn't exist. 

If you have a broken test case - because of the "close tabs" dialog issue - here are a few ways to fix it.
* Consider using `LIKE_NEW` instead, if you don't actually need `BRAND_NEW`.
* Keep using `BRAND_NEW`, but close all tabs in your test that you have created **before** the test is complete to avoid triggering this dialog on quit.
* Deal with the dialog manually in the test, or by writing a helper function.

The `BRAND_NEW` profile is only to be used when you want the behavior of the first-time Firefox user. This particular dialog is just one of those unique situations that a first-time user runs into, so if you truly need the `BRAND_NEW` experience, it's something the test case has to be ready to handle.
