### ISSUE TITLE
[Windows] The background_update test fails to launch when writing pref

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1236]
On Windows, when running this:

`
iris -o -t background_test -f 55.0
`

Iris launches Firefox, but displays the "Unable to connect" page and not the default Iris page. This is because Iris has quit and killed the web server, as it could not find the Iris image in time.

In the test case, if I comment out line 23, everything else works:

`
        self.set_profile_pref('app.update.log;true')
`

I don't know what's changed, but do we need this line?

Also, test eventually fails, but I'm not sure if that's due to a rule change or a genuine failure.

**Comment by silviuFlorin** [comment]
`self.set_profile_pref('app.update.log;true')` is not mandatory in our case so I will remove that line. Test failed  because latest version changed. For less maintenance we could create a method that checks for the latest version per channel so we will have to update only the watershed version in case that changes

**Comment by mwobensmith** [comment]
@silviuFlorin Can you file another issue to capture the work required to create that method?
