### ISSUE TITLE
Make bootstrap script for Windows

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1244]
We can handle most of the project dependencies via a script in the same way we handle Mac/Linux.

**Comment by AndreiH** [comment]
Hi @mwobensmith ! This is now ready for review on branch "issue_1244" https://github.com/mozilla/iris/commit/27134a9aba866748e5ccc26aa4622d63e6c4643e
This was really challenging to finish, because it's very different from Linux and OSX.
We currently install "Scoop" package manager (https://scoop.sh/) which installs all the dependencies, also adds the PATH necessary.

Although the user is prompted to restart the terminal and run the bootstrapt again, because we cannot bypass the fact that the terminal needs to be restarted to recognize the scoop command after the first installation
