### ISSUE TITLE
Performing a 'Code' -> 'Reformat Code' or 'Code' -> 'Optimize Imports' will delete grayed out imports making some tests to fail

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#1287]
Some of our Python files have imports declared that are grayed out. e.g:  
  - test_case.py (from api.core.local_web import LocalWeb),  
  - profile.py(import os), etc

Performing a 'Code' -> 'Reformat Code' or 'Code' -> 'Optimize Imports' will delete them making some tests to fail. 

For example: Test case "awesomebar_search_after_user_input.py" or any other test case that uses LocalWeb will fail after a 'Code' -> 'Reformat Code' or 'Code' -> 'Optimize Imports' is performed on the test_case.py.

**Comment by mwobensmith** [comment]
The problem was that - while nothing in `test_case.py` used `LocalWeb` - classes that inherit from `BaseTest` need `LocalWeb`. The IDE is generally pretty good about inspecting code, but is not able to know what classes in your project inherit from the current class, and therefore might be using a declared import in the current file. 

The easiest fix is to declare something inside `test_case.py` that uses `LocalWeb`, which gets rid of the error and guarantees that we won't delete this import in the future. 😊
