### ISSUE TITLE
bootstrap.sh fails inflating tessdata-3.04.00/yid.traineddata on Ubuntu 16.04

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris#1397]
Running through the setup steps on a new Ubuntu 16.04 install I encounter the following error when bootstrap.sh inflates tessdata-3.04.00/yid.traineddata:

`mkdir: cannot create directory '/usr/local/share/tessdata/': File exists`

If I try to re-run bootstrap.sh I get two more errors:

```
---> installing/upgrading pipenv #####
./bootstrap/linux_bootstrap.sh: line 85: pipenv: command not found
./bootstrap/linux_bootstrap.sh: line 86: pip: command not found
```

**Comment by AndreiH** [comment]
Thanks @ashughes1 for opening and catching this. I don't know how I did not see it.
Actually this was happening because the condition are  inverted here:
```
if command -v pip &>/dev/null; then
    sudo apt-get -y install python-pip
else
    pip install --upgrade pip
fi
```
And pip was not installing.

And for `mkdir: cannot create directory '/usr/local/share/tessdata/': File exists`, this is expected as it should try to create it if it does not exist.

@mwobensmith This is now ready for review on branch `issue_1397`. Thanks !

**Comment by ashughes1** [comment]
Just following up to confirm that this is now fixed on my end. Thank you very much @AndreiH!
