### ISSUE TITLE
Release of Tesseract 4 introduces some issues in Iris on Win 10 (not currently tested on other platforms)

### ISSUE THREAD

**Issue by AndreiH** [mozilla/iris#1410]
Since Tesseract 4 stable version was officially released, `Scoop` installs the latest versions, which is now 4.0.0.
So, who will download Iris from today and run the Win bootstrap, they will have Tesseract 4.
@tracywalker and I have also experienced some issues with tesseract 4 when running the tests.

`failed loading language ‘eng’  Tesseract couldn’t load any languages! Could not initialize Tesseract.`

We need to specify the version of tesseract in the bootstrap.

**Comment by AndreiH** [comment]
```
raise TesseractError(status_code, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, u'Error opening data file C:\\Users\\AH\\scoop\\apps\\tesseract\\current/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')
```

**Comment by mwobensmith** [comment]
It appears that Tesseract is not installing libraries in the correct location(s). @AndreiH has some ideas on how to fix this.

Based on our discussion, we are going to do two things.
1. Disable test cases that use Tesseract in the short term, captured in #1413. 
2. Harden our logic in the bootstrap script to check current Tesseract install. If it has the bug, we can possibly move the files to the right locations, or otherwise work around it.

Once we are sure that either a) our solution works, or b) the problem is fixed upstream, we can turn those tests back on.

**Comment by mwobensmith** [comment]
@AndreiH thinks this is due to libraries not being installed in the correct location, and that we could potentially fix it ourselves.

Based on our conversation, here's what we will do.
1. Disable test cases that use OCR in the short term - #1413.
2. Harden our bootstrap script to see if we can a) detect the buggy config, b) fix it, or c) ignore it. 

This issue can track the work for item #2 above. Eventually it will get fixed upstream, but that doesn't have to hold us back if we feel that we can work around it.

**Comment by AndreiH** [comment]
Seems that `Scoop` already fixed their BUG, YAY !
https://github.com/lukesampson/scoop/issues/2728

**Comment by AndreiH** [comment]
@mwobensmith , this is ready for review on branch `issue_1410`.
This has been tested with different cases. https://github.com/mozilla/iris/commit/ec22dcfb36fb82a2ec3d7bf4f556d653072ff127

Uninstalling other versions and installing Tesseract 3

**Comment by tracywalker** [comment]
Our temporary in house solution was to disable all test case that access ocr in any way with:          self.blocked_by = 'issue 1410'
self.locales = ['en-US']
self.exclude = Platform.ALL

We know it's Windows only and we decided to err on the side of caution.  Once we're certain we can keep Iris users on a compatible version of Tesseract, we'll then re-enable all of the disabled test cases.

**Comment by AndreiH** [comment]
On Linux we install Tesseract 3. On Windows we install Tesseract 3, but on Mac HomeBrew again, does not support versioning of Tesseract, so it installs the latest version.

Fortunately on Mac we don't have the same issue, and the tests that run with Tesseract are working fine. Linux tests were tested also with Tesseract 4 and the issue does not occur.

Although, we all agree that we should have the same version of Tesseract on all Platforms.
I will open an Bug on Tesseract side, explaining what is the Error on Windows. They should fix it and then we can start testing and adding Tesseract 4 to our Project.
