### ISSUE TITLE
Test case: Edit a bookmark from Library

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1619]
https://testrail.stage.mozaws.net/index.php?/cases/view/169268

**Comment by tracywalker** [comment]
this test no longer exists in Testrail

**Comment by tracywalker** [comment]
This test ID was changed. The correct TestRail test case is: https://testrail.stage.mozaws.net/index.php?/cases/view/169268

**Comment by yeyartsev** [comment]
At the last step we need to check  option "Load this bookmark in the sidebar". However, this option was removed since Firefox 63. 
![03_selecting_load_this_bookmark_in_the_sidebar](https://user-images.githubusercontent.com/46671418/57515385-2eeb6200-731b-11e9-9932-1f9cfc3986bb.png)
@tracywalker What should we do with this test?

**Comment by tracywalker** [comment]
ok, just ignore that step.  I'll adjust the test in TestRail.

**Comment by yeyartsev** [comment]
> 
> 
> ok, just ignore that step. I'll adjust the test in TestRail.

Ok, thank you.
