### ISSUE TITLE
Investigate why gihub CI check is no longer being triggered on merge

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#2232]

**Comment by mwobensmith** [comment]
Wondering if [this](https://developer.github.com/changes/2018-04-25-github-services-deprecation/) is the reason...

**Comment by mariusandreifilip** [comment]
Indeed it seems that GitHub Services have been deprecated since 31 January and definitively this affected Travis integration.I'm looking on a solution using webhooks  and come back with more details asap

**Comment by mariusandreifilip** [comment]
So after a closer look I noticed that Github did some changes on the Integration and Services and indeed they deprecated the Services  .From what I saw Travis CI worked with Github to migrate accounts from services to webhooks and here you can find the [Travis change logs ](https://changelog.travis-ci.com/) related to our problem.
The problem here is that I don't have admin access in Iris repo to be able to re install Travis and check if the migration of iris is complete.So here Matt as a first step would be to re install Travis and see if the migration is completed.

**Comment by mwobensmith** [comment]
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1527690

**Comment by tracywalker** [comment]
This works now.
