### ISSUE TITLE
Create shared TestRail account

### ISSUE THREAD

**Issue by dbakaev** [mozilla/iris#2475]
For the integration of Iris and TestRail, we need to have a shared Test Rail account with the permissions of Rest API usage.

**Comment by tracywalker** [comment]
I think it is not possible to create a shared account with the permissions needed to work with the TestRail Rest API.  We created a shared read only account and even it wouldn't work, because of the LDAP requirement.  

Dmitry,  for now,  let's see if we can get the needed permissions on your account.  I think a password token must be created in TestRail.  I believe it may take a TestRail admin to create that.  I'll investigate.

**Comment by tracywalker** [comment]
Dmitry, go to https://testrail.stage.mozaws.net/index.php?/mysettings#. In there is an API Keys tab.  use that to create a unique key

**Comment by dbakaev** [comment]
Unfortunately, token authentication has been disabled for this instance of TestRail server. At attempt to use API key the server throws an error message:

```
{
  "error": "Session authentication is disabled for the API. It can be enabled in the administration area in TestRail under Administration > Site Settings > API."
}
```

Only administrator and enable this option.

**Comment by tracywalker** [comment]
Interesting, I was able to generate a key on my account.  I'll get in touch with the administrator.

**Comment by dbakaev** [comment]
Yes, you can generate a key through Test Rail UI. However, at an attempt to send an API request using that key, the response contains an error message.

**Comment by tracywalker** [comment]
Andrei,  did you run into any similar error when setting up your account to work with the TestRail API?   I don't have admin access to TestRail.  So I couldn't have given your account any special permissions.

**Comment by dbakaev** [comment]
It looks like someone has enabled API authentication via API Keys. Now I am able to access an API.
@tracywalker Thanks for the help!

**Comment by mariusandreifilip** [comment]
Indeed I had the same problems with the auth api's and at that time I
requested a user with special permissions because in order to report result
the user need the ability to create test runs ,plans etc and my user didn't
had those perms.if you look in the IRIS weekly I requested this in
2018-06-20 and you sad that you will help me and the next day I had
rights:).



Thanks,
Andrei Filip

**Comment by tracywalker** [comment]
OK, I think that may have been edit/write access that I had Tom give to you.

Dmitry,  do you have the permission to edit test cases in TestRail, or is your account read only?

**Comment by tracywalker** [comment]
Ooops. Sorry I didn't see Dmitry/s last post.  Odd that it just started working.  We'll take it. :)

**Comment by dbakaev** [comment]
I did not check if my account has write permissions, in fact, I need just read-only access, so I am good now. I think the issue can be closed now.
