### ISSUE TITLE
Fix Firefox defocus after launch under Win 7/10 (intermittent failure)

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris#2659]
There is a problem occurred while running Iris against Windows: sometimes Firefox window, launched with Iris, opens not in focus. Such behaviour could cause test failure.

**Comment by tracywalker** [comment]
I have never seen this happen.  I am curious to first see logs of this and be assured that no accidental outside interaction with mouse/keyboard occurred.

I also do not like this fix. It just assumes that Firefox is in not in focus on each startup instead of checking for focus first  The fix for this issue should be to make confirm_firefox_launch() much more robust by try/wait for Iris page logo, click it if available. If the logo is not available, then try to restore focus, by one at a time, try/wait for elements of Firefox UI, click to get focus and check again for the Iris logo.  If none of those checks work, then we fail out.

**Comment by yeyartsev** [comment]
Thanks, we will look for fix according your approach

**Comment by pavelciapa** [comment]
Changed focus to Iris 2.0
