### ISSUE TITLE
Add ability to restart browser in current test profile

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#45]
This will become required, eventually, as we delve into things like session restore, crash reporting, etc.

**Comment by mwobensmith** [comment]
I think is this pretty easy to do.

**Comment by tracywalker** [comment]
Cool. I would probably tackle as many of the crash reporter tests as possible once this issue was addressed.

**Comment by mwobensmith** [comment]
This is easy to do provided that the test case does not override `setup`, because when the base test case launches Fx, it can keep track of the profile name.  However, if the test decides to override this, it would have to own its own restart logic and/or keep track of the profile name.  I will look into this.
