### ISSUE TITLE
Test 'add_open_delete_bookmarks' currently failing

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#528]
Linux for sure, with intermittent failures on Mac/Win.

**Comment by mwobensmith** [comment]
Your fix contains this:

```
        if Settings.getOS() == Platform.LINUX:
            rightClick(linux_bing_bookmark)
        else:
            rightClick(bing_bookmark)
```

Why not just make a new pattern for `bing_bookmark` on Linux?

**Comment by IonutBudeanu** [comment]
Ok, forgot to mention why I did this.

expected_5 = exists(bing_bookmark, 10)
assert_true(self, expected_5, 'Bing bookmark is present in the sidebar')

In the above assertion we make sure that the bing bookmark is present in the sidebar using the same pattern for all the platforms. In the code snippet that you mentioned I had to take one more pattern for linux because when I try to delete the bookmark from the sidebar, the bookmark have a changed state, basically is selected and has a orange background.

So I need to have the both patterns in the linux folder. First bing_bookmark.png is used in the assertion that I mentioned above and the 2nd one linux_bing_bookmark.png is used only for linux just to be able to delete the bookmark from the sidebar.

Please let me know if everything is clear now.
Thank You

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_528

**Comment by IonutBudeanu** [comment]
This test case doesn't exists anymore. It was split into a multiple test cases due to this [issue](https://github.com/mozilla/iris/issues/681).

Closing this due to issue mentioned above.

Thank You
