### ISSUE TITLE
Test 'hamburger_menu_customize' currently failing

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#530]
Linux only.

**Comment by tracywalker** [comment]
Ioana, this test case fails as written for me on Linux.  If I remove the hard coded use of region when searching for "Drag" the test case passes. I am going to land it as is.  Only because we're going to have to clean up these uses of hard coded regions. Instead we should be opting for regions created with bounds defined by found images.    I would rather us not use .region unless it is impossible to run the test otherwise.   If you're using .region just to help ocr run faster, use pattern matching without region, instead.

**Comment by mwobensmith** [comment]
@silviuFlorin can you help investigate this one?

**Comment by icrisan** [comment]
We managed to reproduce this issue on Paul's machine. Even though the searched text is inside the region created the OCR does not found it. George will take a look on this.

**Comment by silviuFlorin** [comment]
@icrisan This test uses OCR text recognition. Please replace it with a pattern search

**Comment by silviuFlorin** [comment]
Removed an unnecessary time.sleep() call from the test. Code approved
