### ISSUE TITLE
Enable feature to re-run failed tests

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#552]
As discussed in our team meeting,  we would like Iris to have the ability to re-run failed tests after a test run. Iris should smart-merge the results of the test re-runs with the original test run. We would also like Iris to have the ability to control the number of times the original failures are re-run.

**Comment by kimberlythegeek** [comment]
@m8ttyB shared this with me: https://pypi.org/project/pytest-rerunfailures/

Once the API is fully decoupled from the test harness and control center, we can begin using pytest as the test harness instead of wrapping pytest with iris's test harness.

there are many features that already exist in pytest. utilizing would not only eliminate the extra work to create and maintain those features, but would greatly reduce the risk by using a well-maintained project supported by a large community

**Comment by mwobensmith** [comment]
Thanks @kimberlythegeek ! I investigated that one already, but actually found another similar `pytest` plugin that works better - it's called `flaky`.

Since Iris is built around `pytest`, the main work for this is trivial. However, there is also work that goes into `iris_firefox` that is more significant. I will use this issue to track the core work, and [another](https://github.com/mozilla/iris_firefox/issues/3779) in `iris_firefox` for the target work there.
