### ISSUE TITLE
Test 'keyboard_shortcuts' intermittently failing

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#571]
@echim, work with @psilaghi and @mariusandreifilip to see what errors they are getting when they run this test.

**Comment by mwobensmith** [comment]
@silviuFlorin has a fix

**Comment by echim** [comment]
Hi @tracywalker @mwobensmith 
I changed the iris\tests\unit_tests\keyboard_shortcuts.py on branch https://github.com/mozilla/iris/tree/issue_571_2
- there was an issue_571 branch already but it is not related to this issue so I created issue_571_2
- the test was failing because of the offset used on click 
- the fix I applied will always click on the center of the image.

Thank you !

**Comment by mwobensmith** [comment]
Wait and see what happens on Monday's stability run. If it's still failing, get this reviewed with @silviuFlorin . 

If there are no failures, perhaps it's not needed. The test seems to work fine for me right now.

**Comment by silviuFlorin** [comment]
Issue still reproducible on Ionut's machine. Branch issue_571 was created to fix the issue.

**Comment by silviuFlorin** [comment]
Code approved
