### ISSUE TITLE
Test 'bookmarks_menu_and_toolbar' intermittently fails on Linux

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#573]
@mariusandreifilip saw this once on Linux. Can you run with `-i DEBUG` and paste the assert message to this issue, to help @IonutBudeanu figure out what the problem is? Thank you.

**Comment by mariusandreifilip** [comment]
The problem here is the slow netwok and there are some situation when network fluctuations happen to some of us and the amazon logo in this case is not loaded and the test fails.I runned this test also on my personal laptop and I simulated a slow network with a large file download and it's always reproducible on all Os's.

I attached a screenshot with a bookmarked amazon with a broken logo. 
![slow_network_amazon_bookmarks](https://user-images.githubusercontent.com/36045177/41000846-fd3e58a6-6917-11e8-8b44-b291b03bab8d.png)

In this case the fix is  quite easy and removing the url logo should do the trick.

**Comment by mwobensmith** [comment]
I asked to see debug output to know which assert was false, but you did not provide that. 

This issue appears to be the same as #553. We do not want to edit the pattern to make the test pass. The icon is supposed to be displayed. If it does not display, it is a bug. 

It is more related to how long it takes to load the favicon before the Firefox UI is updated. The longer we wait after the page is loaded and bookmarked to access this menu, the more successful we will be. I thought that adding a few seconds after creating the bookmark would help, but that did not work 100% of the time.  

Again, I don't know which assert is failing, so that would help. As far as fixing this, we may have to accept that Linux is slower to update the UI, and add extra time (on Linux only) before accessing the menu.

**Comment by mariusandreifilip** [comment]
Sorry for that I forgot to upload it
[failed_test.txt](https://github.com/mozilla/iris/files/2075228/failed_test.txt)

What should be the approach in this kind of situations?Shoud we increase the exists time wait ?and if so for how long because there are situations when firefox stays more than 15 secs to load a page with a slow network.
The mechanism that Firefox use right now is to wait for DOM complete in order to save the site logo otherwise defaults an internal image that I showed in above comment

**Comment by mwobensmith** [comment]
From our latest stability run, this test only failed once out of 7 people, and only on Linux. So it's not a huge problem. However, it would be nice to solve the problem so that we never have to fix it again.

I think the problem is that Firefox does not display the icon if the Library menu has been opened before the Amazon favicon has been downloaded. Even though the assert in line 125 happens almost a minute after the site has been loaded, it seems that Firefox is caching the default icon. 

What happens if we add more time between bookmarking the page (line 39) and open the Library (line 52)? Perhaps we increase the wait time on line 45 from 2 seconds to 5? It's not the most elegant solution but it seems the least complicated. 

If this doesn't work, we'll look at other ideas.

**Comment by IonutBudeanu** [comment]
I increase the time sleeping on line 45 from 2 to 5 seconds and also changing url2 from "about:home" into "about:blank" just to make sure that we do not have multiple amazon patterns on the page.

The test runs smoothly on Linux. Please take a look at the issue_573 branch -> https://github.com/mozilla/iris/tree/issue_573

**Comment by mwobensmith** [comment]
Landed in dev branch. Let's see how this works in the next stability pass.

**Comment by silviuFlorin** [comment]
@mwobensmith This test failed on my Linux machine today. Assigning issue to Andrei

**Comment by mariusandreifilip** [comment]
Still reproducing on OSX
[add_open_delete_bookmarks.txt](https://github.com/mozilla/iris/files/2101579/add_open_delete_bookmarks.txt)
