### ISSUE TITLE
Update the remove_zoom_indicator_from_toolbar() function from general.py

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#651]
Update the remove_zoom_indicator_from_toolbar() function from general.py to not quit Iris via exit(1) if the zoom indicator is not removed from the toolbar.

**Comment by mwobensmith** [comment]
Thanks @icrisan . Feel free to fix this once #459 has landed, which should be in the next few days.

You can implement solutions similar to other conditions you are covering - log an error message, raise an exception, etc. The only thing we want to avoid right now is `exit`, because of our new multiprocess work. 😃

**Comment by icrisan** [comment]
added branch issue_651. please review.

**Comment by silviuFlorin** [comment]
@icrisan please refer to https://github.com/mozilla/iris/issues/652. There is an example in the comments. API helpers should raise APIHelperError in case they catch any exceptions

**Comment by icrisan** [comment]
@silviuFlorin I updated the helper. please review.

**Comment by silviuFlorin** [comment]
Code approved
