### ISSUE TITLE
Create command-line argument to re-run failures of previous test run

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#701]
This will require us to save a list of failed tests to a reserved location in the .iris working directory. Then, pass it to Iris via the `-t` command line parameter.

**Comment by silviuFlorin** [comment]
This issue depends on https://github.com/mozilla/iris/issues/700

**Comment by silviuFlorin** [comment]
@mwobensmith there are 2 ways we could implement this:
1. Save a list of failed tests and at the end of the run pass that list to Iris via the -t command line parameter

2. As soon as the test fails, re-run it. If a previously failed test passes we will have to override the last outcome in the report rather than searching at the end of the full run for each test that passed the second time and replace the outcome

@mwobensmith which solution do you think we should use?
