### ISSUE TITLE
Split general.py into multiple files

### ISSUE THREAD

**Issue by silviuFlorin** [mozilla/iris#778]
Currently general.py contains all helper functions that are used in our test files. We should split it to better organize our code.

**Comment by silviuFlorin** [comment]
@mwobensmith  
our current structure is:
```
api
    - core
        ...
    - helpers
        ...
        - general.py
        ...
```

There are 2 ways to organize our packages:
1.
```
api
    - core
        ...
    - helpers
        - core_helpers
            ...
        - test_helpers 
            ...
```

2. 
```
api
    - core
        ...
    - core_helpers
        ...
    - test_helpers 
            ...
```
Which one do you think is better?

**Comment by GriffinAustin** [comment]
@silviuFlorin The second one seems more intuitive. Why would core be included in helpers? Plus, if we are splitting general.py, we should only split it into its current directory and not mess with other files unless there is a good reason to. Thoughts?

**Comment by tracywalker** [comment]
I'm of the thinking that general.py simply needs to be better organized within itself, categorized and alphabetized within the categories.

**Comment by mwobensmith** [comment]
I want to move `Profile` and `LocalWeb` classes out of `general.py` and into `core` somewhere. 

Otherwise, it comes down to three categories of functions here:
* helper functions intended to be used by test cases (`navigate`, `open_library_menu`, `restart_firefox`)
* functions used indirectly by test cases, and/or by other parts of Iris (`write_profile_prefs`, `create_firefox_args`, `address_crash_reporter`, `confirm_firefox_launch`)
* `get_menu_modifier` and `get_main_modifier` should be moved into `keyboard_shortcuts.py`, or deleted, since we don't seem to be using them anywhere.

I'd probably call the first category of functions above `firefox`, since they all pertain to interacting with the browser - specifically UI. You could consider other subcategories like "window"/"menu"/etc. but the list is not so large right now that we need to do so. 

I'd call the second category `general` and just keep them in `general.py`.

**Comment by mwobensmith** [comment]
All new structure in Iris 2.0.
