### ISSUE TITLE
Investigate and fixes a few failing bookmarks test cases on Mac non-retina

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#808]
bookmark_via_url_sidebar(1), bookmark_via_url_toolbar(2), change_bookmark_location and change_bookmark_name all fail on Mac non-retina.  They work fine on Mac retina screen.

1, 2, and 3 all fail in a dragDrop operation. The drag pickup isn't finding the image. Please assert that the image is found first, like in zoom_controls_on_toolbar.py (lines 46-49).

Also, 1 and 2 are falsely reporting that the star button has changed to blue when it actually hasn't.

in test 4 , Iris isn't finding a match on screen for the image of modified_bookmark.png even though it does exist on screen.

Please investigate and fix these issues.

**Comment by tracywalker** [comment]
Ideally, both images (drag_from and drag_to) passed into dragDrop() should be checked for existence inside the DnD function before attempting the DnD operation.

**Comment by IonutBudeanu** [comment]
I ran the bookmark test suite on non-retina Mac with latest dev and each test case have as outcome PASSED.

Please take a look and close the issue if you agree.

Thank You :).

**Comment by IonutBudeanu** [comment]
I ran for the 3rd time the bookmark test suite (on non-retina MAC)  and i noticed that we actually have a problem with firefox restart, and also with the 'Firefox quit unexpected..' pop up. 

Each test case passes individually but it's a problem when the tests are run as suite. I saw that we definitely have a problem with bookmark_from_private_browsing because inside the test case an restart is required and the next test case will gonna fail as well because the restart is not performed accordingly. 

I will continue to investigate this and @tracywalker  please let me know what you think about that.

Thank You
