### ISSUE TITLE
Develop test case: Delete a page from the Library - History menu

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#903]
https://testrail.stage.mozaws.net/index.php?/cases/view/174048

**Comment by wizofe** [comment]
I would like to give a go to this test case. I am applying for Outreachy and I want to understand better the test codebase. By reading the [wiki](https://github.com/mozilla/iris/wiki/Contributions), I found out that test cases are the best way to get started! 

I have a Mozillians account (not verified though) but still can't access that page. Any way that you can share that otherwise? ta

**Comment by tracywalker** [comment]
test case steps with expected results (after pipe):

1. Select the History option from the View History, saved bookmarks and more Menu. | History menu is displayed.
2. Click on the Show All History button. | The Library is correctly displayed, with the History section in focus.
3. Right click on a website from the History section and select Delete Page option. | The page is deleted from the History bar and from the History menu as well.

**Comment by alinrus** [comment]
Coverage added in branch 'issue_903'. @tracywalker please review.

**Comment by tracywalker** [comment]
code approved
