### ISSUE TITLE
Update existing bookmark tests in order to use local sites and local profiles

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#917]
The tests that needs to be modified are as follow:

- bookmark_from_private_browsing.py

- bookmark_via_keyboard_shortcut.py

- bookmark_via_star_button.py

- bookmark_via_url_sidebar.py

- bookmark_via_url_toolbar.py

- bookmarks_toolbar_search.py

- change_bookmark_location.py

- change_bookmark_name.py

- copy_context_menu.py

- cut_context_menu.py

- enable_bookmarks_sidebar_from_bookmarks_menu.py

- enable_bookmarks_toolbar_from_bookmarks_menu.py

- load_bookmark_inside_the_sidebar.py

- open_bookmark_from_bookmarks_menu.py

- open_bookmark_from_bookmarks_toolbar.py

- open_bookmark_from_library.py

- open_bookmark_from_sidebar.py

- remove_bookmark_from_bookmarks_menu.py

- remove_bookmark_from_library.py

- remove_bookmark_from_sidebar.py

**Comment by IonutBudeanu** [comment]
First 5 test cases have been updated in issue_917_1 branch.

Please review.

Thank You.

**Comment by tracywalker** [comment]
Ionut, the first 5 updated tests look good.  However, you don't need to override the profile to be LIKE_NEW, as LIKE_NEW is the default profile in Iris. (see line #30 at https://github.com/mozilla/iris/blob/master/iris/api/core/profile.py) Please remove this code in each of your test cases.  

Also, since you're just starting this, you might as well fix all of the pattern declarations as you go.
so for example, instead of:
drag_area = 'drag_area.png'
convert it to:  
drag_area = Pattern('drag_area.png')

It's a simple fix for each image declaration.

**Comment by IonutBudeanu** [comment]
Hi Tracy,

I used LIKE_NEW profile in tests because I had some problems with a pop after restart that ask user to use Firefox as default browser. But you're right, I missed that LIKE_NEW is the default profile in Iris.

And of course, I will fix the pattern declarations.

Thank You

**Comment by silviuFlorin** [comment]
Code approved

**Comment by IonutBudeanu** [comment]
Second set of updated bookmark tests is up in issue_917_2 branch.

Please review.

Thank You

**Comment by tracywalker** [comment]
Ionut, Please investigate and address the following:

change_bookmark_name.py fails for me on Windows. Once the test begins, the browser window is reduced to about 20% of entire screen, instead of full screen. If I insert maximize_window() before the first test step of navigate('about:blank')  the test will run. Does the TEN_BOOKMARKS profile on Windows open too small?  (On Windows, the browser is opening too small in any test that uses the TEN_BOOKMARKS profile)

Also, in the same test case, on all platforms, I am seeing random failures in try: wait(changed_toolbar_bookmark_pattern, 10).

Linux is failing randomly in copy_context_menu line 77

Please make sure all of the error messages in each test case are PEP8 compliant with '.' punctuation at the end of each message.

Lastly, I'd like this test directory 'bookmark_test' to be changed to 'bookmark'.

**Comment by IonutBudeanu** [comment]
HI Tracy,

I ran the change_bookmark_name.py test and also copy_context_menu.py for 10 times on all the platforms and I'm still not able to reproduce the errors that you mentioned. Everything works fine for me on all the platforms on issue_917_2 branch.

I pushed the changes with '.' punctuation and also with the test directory name changed to 'bookmark'.

If you can please provide more details about the errors that you receive in the specified tests.

Thank You

**Comment by tracywalker** [comment]
issue_917_2 code approved

**Comment by IonutBudeanu** [comment]
Third set of updated bookmark tests is up in issue_917_3 branch.

Please review.

Thank You

**Comment by tracywalker** [comment]
regarding issue_917_3, load_bookmark_inside_the_sidebar fails to find the scroll bar. The error message implies it can't find horizontal scroll, (which is actually on screen)  but the image for sidebar_scroll is of a vertical slider.

I am ot sure what is going on but in my pull of your issue_917_3, you have duplicated "bookmark_test" directory with a copy as 'bookmark". We just want the original renamed.  You should be able to do this with git mv bookmark_test bookmark. That will only work if you remove the duplicate you created.

**Comment by IonutBudeanu** [comment]
Hi Tracy,

I updated the sidebar_scroll image and everything works fine now. Initially I thought that this test is just for the firefox versions under 62 and that's why i left the old sidebar_scroll as it was.

Regarding the ghost 'bookmark_test" folder is just a local signature in Pycharm. If you take a look at the branch in Github you'll gonna see that everything is fine there, only the refactored directory is present (**bookmark**). In order to remove the ghost directory please just delete it from Pycharm locally, and after that everything will be fine, even if you'll gonna pull the branch again.

Thank you and please let me know if you have another questions.

**Comment by tracywalker** [comment]
code approved - pending rebase

**Comment by IonutBudeanu** [comment]
Fourth and the last set of updated bookmark tests is up in issue_917_4 branch.

Please review.

Thank You

**Comment by tracywalker** [comment]
917_4 code approved
